# Generated by Django 2.2.1 on 2019-05-15 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='书名')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='bbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色名')),
                ('gender', models.CharField(choices=[('a', '男'), ('2', '女')], max_length=10, verbose_name='性别')),
                ('skill', models.CharField(max_length=50, null=True, verbose_name='绝招')),
                ('boot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.aaa', verbose_name='书')),
            ],
        ),
    ]
